name: proto_eqla
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.7
  - jupyterlab
  - pip
  - pip:
    - easyocr==1.4.1
    - opencv-python==4.6.0.66
    - openai==0.19.0
    - flask==2.1.2
    - gtts==2.2.4